[window]
opacity=0.92
[window.padding]
y = 25 
x = 25  

[font]
normal = { family = "Libertinus Mono", style = "SemiThin" }
# normal = { family = "JetBrainsMono", style = "SemiThin" }
size = 14
offset = {x = -2}



[colors.primary]
background = "#1a1310"
foreground = "#e0c9b8"

[colors.normal]
black   = "#1a1310"
red     = "#9e3b3b"
green   = "#8a7a4a"
yellow  = "#c9a24a"
blue    = "#7a4a3a"
magenta = "#a85c4a"
cyan    = "#a88a76"
white   = "#e0c9b8"

[colors.bright]
black   = "#2b1f1a"
red     = "#b85050"
green   = "#a8944a"
yellow  = "#e0b85a"
blue    = "#9a6050"
magenta = "#c07a60"
cyan    = "#c9b09a"
white   = "#f0e2d4"
